### ISSUE TITLE
How to extract the inversions from the dipcall results?

### ISSUE THREAD

**Issue by biozzq** [lh3/dipcall#11]
Dear @lh3 ,

After running `dipcall`, it will generate a file named `${pre}.dip.vcf.gz`. All the genetic variants including SNVs, Indels, and SVs are all deposited in this VCF file. I know i can separate these variants according the length of the reference allele and alternative allele. However, i do not know  to extract the inversions from this VCF file?

Looking forward to your reply, thanks.

Sincerely yours,
Zheng zhuqing

**Comment by lh3** [comment]
Dipcall doesn't call inversions.
