### ISSUE TITLE
Using winnowmap

### ISSUE THREAD

**Issue by steven-solar** [lh3/dipcall#12]
Attempted to run dipcall using winnowmap (by passing `-W repetitive_k15.txt`) and saw the following error in `dipcall.hap1.paf.gz.log`:
```
[M::mm_idx_gen::0.003*1.15] reading downweighted kmers
ERROR: input list of k-mers and winnowmap parameter k are inconsistent
```
My repetitive_kmer file is of the form:
```
CGGAATTGAATGGAA	18274
CTCAAAAACAAAAAA	4552
CGGAATTGAATGGAA	12469
...
```
Unless there is a way to pass a value for k to dipcall, what value of k does dipcall anticipate? I did not see it listed in the documentation, or in the error message. I know `k=15` is the default for winnowmap, which is why I tried that first.

**Comment by lh3** [comment]
You are doing assembly alignment. Winnowmap2 uses 19-mer by default.
