### ISSUE TITLE
Interpretation of dipcall vcf file

### ISSUE THREAD

**Issue by nirvana693** [lh3/dipcall#13]
Dear @lh3,
Thank you for great tools. 

I have phased human genome (using trio data) assembly generated from hifiasm. I have generated dipcall results by aligning hap1 and hap2 assemblies to CHM13 genome. Below are the results of filter column-
```
5134326 .
   5318 DIPY
 144669 GAP1
    548 GAP1;DIPY
  14048 GAP1;HET2
 159554 GAP2
  48065 HET1
  87672 HET1;GAP2
  17434 HET1;HET2
  34374 HET2
``` 
May I know how to interpret these results in terms of assembly quality?

**Comment by lh3** [comment]
see vcf header
