### ISSUE TITLE
Reducing alignment size

### ISSUE THREAD

**Issue by malmarri** [lh3/dipcall#2]
Hi 

From the README:

"A raw variant call is made in the VCF if a non-reference allele is observed in any alignments >=50kb and mapped with mapping quality >=5."

Is it possible to have an option to reduce the alignment length like in paftools call -L?

Thanks

**Comment by lh3** [comment]
Not possible at the moment. The threshold is hard coded. Dipcall is generally designed for high-quality assemblies. The contig N50 needs to reach a few megabase at least.
